# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0154bc4277e9d9e656bc4fa24f4d285ba2864ac1b6b81b5a1fdfbb2bd9a014973b0b5ef9b20fa5989c0e797f73d365f77c7cfed8414a6aa4b5681d9d5c94872
  sorcery_twitter_callback_url: http://0.0.0.0:3000/oauth/callback?provider=twitter
  sorcery_twitter_key: <%= ENV["SORCERY_TWITTER_KEY"] %>
  sorcery_twitter_secret: <%= ENV["SORCERY_TWITTER_SECRET"] %>

test:
  secret_key_base: 2a8df474cccd3fcb08b0b2b804e2fbba5c5088e78257108bc443e2cf4b0f2b4f3fcbfee59ffe58406adb9046845c746e134b935014a9bbf9bfec7370868fc33e
  sorcery_twitter_key: <%= ENV["SORCERY_TWITTER_KEY"] %>
  sorcery_twitter_secret: <%= ENV["SORCERY_TWITTER_SECRET"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  sorcery_github_callback_url: <%= ENV["SORCERY_TWITTER_CALLBACK_URL"] %>
  sorcery_twitter_key: <%= ENV["SORCERY_TWITTER_KEY"] %>
  sorcery_twitter_secret: <%= ENV["SORCERY_TWITTER_SECRET"] %>
#7f5e453ea15c9b5d3045b34138358530b474ebc9b904fdbb064ae5079e908d27128cafcede8df98578795b38587e4711ef9b5bd911c350be9f6bad1a8d539067
